[package]
name = "rusk-vm"
version = "0.6.0-rc.0"
authors = [
  "Kristoffer Ström <kristoffer@dusk.network>",
  "zer0 <matteo@dusk.network>"
]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
failure = "0.1"

dusk-abi = "0.9.0-rc"

canonical = "0.6"
canonical_derive = "0.6"
dusk-hamt = "0.2"

[dev-dependencies]
dusk-bls12_381 = "0.8"
dusk-bytes = "0.1"
dusk-poseidon = "0.21.0-rc"
criterion = "0.3"


# test contracts
counter = { path = "tests/contracts/counter" }
fibonacci = { path = "tests/contracts/fibonacci" }
delegator = { path = "tests/contracts/delegator" }
stack = { path = "tests/contracts/stack" }
block_height = { path = "tests/contracts/block_height" }
self_snapshot = { path = "tests/contracts/self_snapshot" }
host_fn = { path = "tests/contracts/host_fn" }
tx_vec = { path = "tests/contracts/tx_vec" }

[[bench]]
name = "fibonacci"
harness = false

[workspace]

members = [
    "tests/contracts/*",
]